export default cantones = [
    {canton: 'San José', cabecera: 'San José'},
    {canton: 'Escazú', cabecera: 'Escazú'},
    {canton: 'Desamparados', cabecera: 'Desamparados'},
    {canton: 'Puriscal', cabecera: 'Santiago'},
    {canton: 'Tarrazú', cabecera: 'San Marcos'},
    {canton: 'Aserrí', cabecera: 'Aserrí'},
    {canton: 'Mora', cabecera: 'Ciudad Colón'},
    {canton: 'Goicoechea', cabecera: 'Guadalupe'},
    {canton: 'Santa Ana', cabecera: 'Santa Ana'},
    {canton: 'Alajuelita', cabecera: 'Alajuelita'},
    {canton: 'Vásquez de Coronado', cabecera:'San Isidro'},
    {canton: 'Acosta', cabecera: 'San Ignacio'},
    {canton: 'Tibás', cabecera: 'San Juan'},
    {canton: 'Moravia', cabecera: 'San Vicente'},
    {canton: 'Montes de Oca', cabecera: 'San Pedro'},
    {canton: 'Turrubares', cabecera:'San Pablo'},
    {canton: 'Dota', cabecera:'Santa María'},
    {canton: 'Curridabat', cabecera:'Curridabat'},
    {canton: 'Pérez Zeledón', cabecera: 'San Isidro de El General'},
    {canton: 'León Cortéz', cabecera: 'San Pablo'}
]